In [219]:
from geopy import geocoders

In [220]:
import pandas as pd

In [221]:
g = geocoders.GoogleV3("AIzaSyCqTMWCA9KPXuNoBfNsd6e2UiMkOgavPDY")

In [222]:
#testing
g.geocode("Spain")

Location(Spain, (40.46366700000001, -3.74922, 0.0))

In [248]:
forest=pd.read_csv('forest.csv')

In [249]:
forest.head(6)

       Country       2015
0        Aruba   2.333333
1  Afghanistan   2.067825
2       Angola  46.407315
3      Albania  28.156934
4      Andorra  34.042553
5   Arab World   2.802680

In [251]:
countryList=forest['Country']

In [121]:
type(GDP)

pandas.core.frame.DataFrame

In [122]:
countryArray=GDP['country']

In [123]:
valueArray=GDP['2015Map']

In [125]:
valueArray

0         1
1         2
2         9
3         2
4         1
5       192
6        28
7        45
8         2
9         1
10        1
11      101
12       30
13        5
14        1
15       35
16        2
17        2
18       16
19        5
20        3
21        2
22        2
23        5
24        1
25        1
26        3
27      136
28        1
29        2
       ...
162       1
163       1
164       4
165       1
166       1
167       8
168       4
169      38
170       1
171       2
172       1
173      31
174       2
175       4
176       1
177       4
178      65
179       1
180       4
181       3
182       8
183       5
184    1353
185       6
186      15
187       1
188       1
189      25
190       3
191       2
Name: 2015Map, Length: 192, dtype: int64

In [252]:
#get the lat/long coordinates of the countries
for country in countryList:
            placemark = g.geocode(country)
            print ( placemark[1][0],',' ,placemark[1][1],',')

12.52111 , -69.968338 ,
33.93911 , 67.709953 ,
-11.202692 , 17.873887 ,
41.153332 , 20.168331 ,
42.506285 , 1.521801 ,
33.82367 , -117.960126 ,
23.424076 , 53.847818 ,
-38.416097 , -63.61667199999999 ,
40.069099 , 45.038189 ,
-14.270972 , -170.132217 ,
17.060816 , -61.796428 ,
-25.274398 , 133.775136 ,
47.516231 , 14.550072 ,
40.143105 , 47.576927 ,
-3.373056 , 29.918886 ,
50.503887 , 4.469936 ,
9.30769 , 2.315834 ,
12.238333 , -1.561593 ,
23.684994 , 90.356331 ,
42.733883 , 25.48583 ,
26.0667 , 50.5577 ,
25.03428 , -77.39627999999999 ,
43.915886 , 17.679076 ,
53.709807 , 27.953389 ,
17.189877 , -88.49765 ,
32.3078 , -64.7505 ,
-16.290154 , -63.58865299999999 ,
-14.235004 , -51.92528 ,
13.193887 , -59.543198 ,
4.535277 , 114.727669 ,
27.514162 , 90.433601 ,
-22.328474 , 24.684866 ,
6.611110999999999 , 20.939444 ,
56.130366 , -106.346771 ,
54.5259614 , 15.2551187 ,
46.818188 , 8.227511999999999 ,
34.1819189 , -119.2291726 ,
-35.675147 , -71.542969 ,
35.86166 , 104.195397 ,
7.539988999999999 , -5.547079999999999 ,
7.369721999999999 , 12.354722 ,
-4.038333 , 21.758664 ,
-0.228021 , 15.827659 ,
4.570868 , -74.297333 ,
-11.6455 , 43.3333 ,
16.5388 , -23.0418 ,
9.748916999999999 , -83.753428 ,
21.521757 , -77.781167 ,
35.126413 , 33.429859 ,
49.81749199999999 , 15.472962 ,
51.165691 , 10.451526 ,
11.825138 , 42.590275 ,
15.414999 , -61.37097600000001 ,
56.26392 , 9.501785 ,
18.735693 , -70.162651 ,
28.033886 , 1.659626 ,
-1.831239 , -78.18340599999999 ,
26.820553 , 30.802498 ,
15.179384 , 39.782334 ,
40.46366700000001 , -3.74922 ,
58.595272 , 25.0136071 ,
9.145000000000001 , 40.489673 ,
61.92410999999999 , 25.7481511 ,
-17.713371 , 178.065032 ,
46.227638 , 2.213749 ,
61.89263500000001 , -6.9118061 ,
7.425554 , 150.550812 ,
-0.803689 , 11.609444 ,
55.378051 , -3.435973 ,
32.1656221 , -82.9000751 ,
7.946527 , -1.023194 ,
36.140751 , -5.353585 ,
9.945587 , -9.696645 ,
13.443182 , -15.310139 ,
11.803749 , -15.180413 ,
1.650801 , 10.267895 ,
39.074208 , 21.824312 ,
12.1165 , -61.67899999999999 ,
71.706936 , -42.604303 ,
15.783471 , -90.23075899999999 ,
13.444304 , 144.793731 ,
4.860416 , -58.93018 ,
22.396428 , 114.109497 ,
15.199999 , -86.241905 ,
45.1 , 15.2000001 ,
18.971187 , -72.285215 ,
47.162494 , 19.5033041 ,
-0.789275 , 113.921327 ,
20.593684 , 78.96288 ,
53.1423672 , -7.692053599999999 ,
32.427908 , 53.688046 ,
33.223191 , 43.679291 ,
64.963051 , -19.020835 ,
31.046051 , 34.851612 ,
41.87194 , 12.56738 ,
18.109581 , -77.297508 ,
30.585164 , 36.238414 ,
36.204824 , 138.252924 ,
48.019573 , 66.923684 ,
-0.023559 , 37.906193 ,
41.20438 , 74.766098 ,
12.565679 , 104.990963 ,
-3.370417 , -168.734039 ,
35.907757 , 127.766922 ,
29.31166 , 47.481766 ,
19.85627 , 102.495496 ,
33.854721 , 35.862285 ,
6.428055 , -9.429499000000002 ,
26.3351 , 17.228331 ,
47.166 , 9.555373 ,
55.169438 , 23.881275 ,
49.815273 , 6.129582999999999 ,
56.879635 , 24.603189 ,
22.198745 , 113.543873 ,
31.791702 , -7.092619999999999 ,
47.411631 , 28.369885 ,
-18.766947 , 46.869107 ,
3.202778 , 73.22068 ,
29.2985278 , 42.5509603 ,
23.634501 , -102.552784 ,
36.958014 , -94.79361899999999 ,
41.608635 , 21.745275 ,
17.570692 , -3.996166 ,
35.937496 , 14.375416 ,
21.916221 , 95.955974 ,
46.862496 , 103.846656 ,
-18.665695 , 35.529562 ,
21.00789 , -10.940835 ,
-20.348404 , 57.55215200000001 ,
-13.254308 , 34.301525 ,
4.210484 , 101.975766 ,
-22.95764 , 18.49041 ,
-20.904305 , 165.618042 ,
17.607789 , 8.081666 ,
9.081999 , 8.675277 ,
12.865416 , -85.207229 ,
52.132633 , 5.291265999999999 ,
60.47202399999999 , 8.468945999999999 ,
28.394857 , 84.12400799999999 ,
-0.522778 , 166.931503 ,
-40.900557 , 174.885971 ,
21.4735329 , 55.975413 ,
30.375321 , 69.34511599999999 ,
8.537981 , -80.782127 ,
-9.189967 , -75.015152 ,
12.879721 , 121.774017 ,
7.514979999999999 , 134.58252 ,
40.339852 , 127.510093 ,
39.39987199999999 , -8.224454 ,
-23.442503 , -58.443832 ,
29.9714142 , 31.2213144 ,
25.354826 , 51.183884 ,
45.943161 , 24.96676 ,
61.52401 , 105.318756 ,
-1.940278 , 29.873888 ,
23.885942 , 45.079162 ,
12.862807 , 30.217636 ,
14.497401 , -14.452362 ,
1.352083 , 103.819836 ,
-9.64571 , 160.156194 ,
43.94236 , 12.457777 ,
5.152149 , 46.199616 ,
44.016521 , 21.005859 ,
0.18636 , 6.613080999999999 ,
3.919305 , -56.027783 ,
48.669026 , 19.699024 ,
46.151241 , 14.995463 ,
60.12816100000001 , 18.643501 ,
-26.522503 , 31.465866 ,
15.454166 , 18.732207 ,
8.619543 , 0.824782 ,
15.870032 , 100.992541 ,
38.861034 , 71.276093 ,
38.969719 , 59.556278 ,
-21.178986 , -175.198242 ,
33.886917 , 9.537499 ,
38.963745 , 35.243322 ,
-7.109534999999999 , 177.64933 ,
-6.369028 , 34.888822 ,
1.373333 , 32.290275 ,
48.379433 , 31.1655799 ,
-32.522779 , -55.765835 ,
37.09024 , -95.712891 ,
41.377491 , 64.585262 ,
14.058324 , 108.277199 ,
-15.376706 , 166.959158 ,
42.6026359 , 20.902977 ,
-30.559482 , 22.937506 ,
-13.133897 , 27.849332 ,
-19.015438 , 29.154857 ,

In [271]:
forestFinal=pd.read_csv('forestFinal.csv',names=None,header=None)

In [272]:
forestFinal

             0           1     2  3
0    12.521110  -69.968338    40  2
1    33.939110   67.709953    36  2
2   -11.202692   17.873887   788  2
3    41.153332   20.168331   478  2
4    42.506285    1.521801   578  2
5    33.823670 -117.960126    48  2
6    23.424076   53.847818    67  2
7   -38.416097  -63.616672   169  2
8    40.069099   45.038189   198  2
9   -14.270972 -170.132217  1488  2
10   17.060816  -61.796428   378  2
11  -25.274398  133.775136   276  2
12   47.516231   14.550072   796  2
13   40.143105   47.576927   234  2
14   -3.373056   29.918886   183  2
15   50.503887    4.469936   383  2
16    9.307690    2.315834   649  2
17   12.238333   -1.561593   333  2
18   23.684994   90.356331   187  2
19   42.733883   25.485830   598  2
20   26.066700   50.557700    14  2
21   25.034280  -77.396280   873  2
22   43.915886   17.679076   724  2
23   53.709807   27.953389   723  2
24   17.189877  -88.497650  1017  2
25   32.307800  -64.750500   340  2
26  -16.290154  -63.588653   858  2
27  -14.235004  -51.925280  1003  2
28   13.193887  -59.543198   249  2
29    4.535277  114.727669  1223  2
..         ...         ...   ... ..
153   1.352083  103.819836   392  2
154  -9.645710  160.156194  1325  2
155   5.152149   46.199616   173  2
156  44.016521   21.005859   528  2
157   0.186360    6.613081   948  2
158   3.919305  -56.027783  1668  2
159  48.669026   19.699024   685  2
160  46.151241   14.995463  1052  2
161  60.128161   18.643501  1170  2
162 -26.522503   31.465866   578  2
163  15.454166   18.732207    67  2
164   8.619543    0.824782    59  2
165  15.870032  100.992541   545  2
166  38.861034   71.276093    51  2
167  38.969719   59.556278   150  2
168 -21.178986 -175.198242   213  2
169  33.886917    9.537499   114  2
170  38.963745   35.243322   259  2
171  -7.109535  177.649330   566  2
172  -6.369028   34.888822   883  2
173   1.373333   32.290275   177  2
174  48.379433   31.165580   283  2
175 -32.522779  -55.765835   180  2
176  37.090240  -95.712891   576  2
177  41.377491   64.585262   129  2
178  14.058324  108.277199   809  2
179 -15.376706  166.959158   613  2
180 -30.559482   22.937506   130  2
181 -13.133897   27.849332  1110  2
182 -19.015438   29.154857   618  2

[183 rows x 4 columns]

In [273]:

for i in range(0,183):
    for j in range(0,4):
        print(forestFinal.iloc[i,j],',')

12.52111 ,
-69.968338 ,
40 ,
2 ,
33.93911 ,
67.709953 ,
36 ,
2 ,
-11.202692 ,
17.873887 ,
788 ,
2 ,
41.153332 ,
20.168331 ,
478 ,
2 ,
42.506285 ,
1.521801 ,
578 ,
2 ,
33.82367 ,
-117.960126 ,
48 ,
2 ,
23.424076 ,
53.847818 ,
67 ,
2 ,
-38.416097 ,
-63.616672 ,
169 ,
2 ,
40.069099 ,
45.038189 ,
198 ,
2 ,
-14.270972 ,
-170.132217 ,
1488 ,
2 ,
17.060816 ,
-61.796428 ,
378 ,
2 ,
-25.274398 ,
133.775136 ,
276 ,
2 ,
47.516231 ,
14.550072 ,
796 ,
2 ,
40.143105 ,
47.576927 ,
234 ,
2 ,
-3.373056 ,
29.918886 ,
183 ,
2 ,
50.503887 ,
4.469936 ,
383 ,
2 ,
9.30769 ,
2.315834 ,
649 ,
2 ,
12.238333 ,
-1.561593 ,
333 ,
2 ,
23.684994 ,
90.356331 ,
187 ,
2 ,
42.733883 ,
25.48583 ,
598 ,
2 ,
26.0667 ,
50.5577 ,
14 ,
2 ,
25.03428 ,
-77.39628 ,
873 ,
2 ,
43.915886 ,
17.679076 ,
724 ,
2 ,
53.709807 ,
27.953389 ,
723 ,
2 ,
17.189877 ,
-88.49765 ,
1017 ,
2 ,
32.3078 ,
-64.7505 ,
340 ,
2 ,
-16.290154 ,
-63.588653 ,
858 ,
2 ,
-14.235004 ,
-51.92528 ,
1003 ,
2 ,
13.193887 ,
-59.543198 ,
249 ,
2 ,
4.535277 ,
114.727669 ,
1223 ,
2 ,
27.514162 ,
90.433601 ,
1227 ,
2 ,
-22.328474 ,
24.684866 ,
325 ,
2 ,
6.611111 ,
20.939444 ,
604 ,
2 ,
56.130366 ,
-106.346771 ,
648 ,
2 ,
54.5259614 ,
15.2551187 ,
581 ,
2 ,
46.818188 ,
8.227512 ,
539 ,
2 ,
34.1819189 ,
-119.2291726 ,
73 ,
2 ,
-35.675147 ,
-71.542969 ,
405 ,
2 ,
35.86166 ,
104.195397 ,
378 ,
2 ,
7.539989 ,
-5.54708 ,
556 ,
2 ,
7.369722 ,
12.354722 ,
676 ,
2 ,
-4.038333 ,
21.758664 ,
1143 ,
2 ,
-0.228021 ,
15.827659 ,
1110 ,
2 ,
4.570868 ,
-74.297333 ,
895 ,
2 ,
-11.6455 ,
43.3333 ,
338 ,
2 ,
16.5388 ,
-23.0418 ,
379 ,
2 ,
9.748917 ,
-83.753428 ,
916 ,
2 ,
21.521757 ,
-77.781167 ,
523 ,
2 ,
35.126413 ,
33.429859 ,
318 ,
2 ,
49.817492 ,
15.472962 ,
587 ,
2 ,
51.165691 ,
10.451526 ,
556 ,
2 ,
11.825138 ,
42.590275 ,
5 ,
2 ,
15.414999 ,
-61.370976 ,
981 ,
2 ,
56.26392 ,
9.501785 ,
248 ,
2 ,
18.735693 ,
-70.162651 ,
697 ,
2 ,
28.033886 ,
1.659626 ,
15 ,
2 ,
-1.831239 ,
-78.183406 ,
858 ,
2 ,
26.820553 ,
30.802498 ,
2 ,
2 ,
15.179384 ,
39.782334 ,
254 ,
2 ,
40.463667 ,
-3.74922 ,
625 ,
2 ,
58.595272 ,
25.0136071 ,
893 ,
2 ,
9.145 ,
40.489673 ,
213 ,
2 ,
61.92411 ,
25.7481511 ,
1241 ,
2 ,
-17.713371 ,
178.065032 ,
945 ,
2 ,
46.227638 ,
2.213749 ,
527 ,
2 ,
61.892635 ,
-6.9118061 ,
2 ,
2 ,
7.425554 ,
150.550812 ,
1558 ,
2 ,
-0.803689 ,
11.609444 ,
1514 ,
2 ,
55.378051 ,
-3.435973 ,
221 ,
2 ,
32.1656221 ,
-82.9000751 ,
690 ,
2 ,
7.946527 ,
-1.023194 ,
697 ,
2 ,
9.945587 ,
-9.696645 ,
440 ,
2 ,
13.443182 ,
-15.310139 ,
818 ,
2 ,
11.803749 ,
-15.180413 ,
1190 ,
2 ,
1.650801 ,
10.267895 ,
949 ,
2 ,
39.074208 ,
21.824312 ,
534 ,
2 ,
12.1165 ,
-61.679 ,
848 ,
2 ,
71.706936 ,
-42.604303 ,
1 ,
2 ,
15.783471 ,
-90.230759 ,
561 ,
2 ,
13.444304 ,
144.793731 ,
786 ,
2 ,
4.860416 ,
-58.93018 ,
1424 ,
2 ,
15.199999 ,
-86.241905 ,
697 ,
2 ,
45.1 ,
15.2000001 ,
583 ,
2 ,
18.971187 ,
-72.285215 ,
61 ,
2 ,
47.162494 ,
19.5033041 ,
388 ,
2 ,
-0.789275 ,
113.921327 ,
853 ,
2 ,
20.593684 ,
78.96288 ,
404 ,
2 ,
53.1423672 ,
-7.6920536 ,
187 ,
2 ,
32.427908 ,
53.688046 ,
113 ,
2 ,
33.223191 ,
43.679291 ,
33 ,
2 ,
64.963051 ,
-19.020835 ,
9 ,
2 ,
31.046051 ,
34.851612 ,
130 ,
2 ,
41.87194 ,
12.56738 ,
537 ,
2 ,
18.109581 ,
-77.297508 ,
526 ,
2 ,
30.585164 ,
36.238414 ,
19 ,
2 ,
36.204824 ,
138.252924 ,
1162 ,
2 ,
48.019573 ,
66.923684 ,
22 ,
2 ,
-0.023559 ,
37.906193 ,
133 ,
2 ,
41.20438 ,
74.766098 ,
58 ,
2 ,
12.565679 ,
104.990963 ,
909 ,
2 ,
-3.370417 ,
-168.734039 ,
255 ,
2 ,
35.907757 ,
127.766922 ,
1077 ,
2 ,
29.31166 ,
47.481766 ,
7 ,
2 ,
19.85627 ,
102.495496 ,
1379 ,
2 ,
33.854721 ,
35.862285 ,
228 ,
2 ,
6.428055 ,
-9.429499 ,
737 ,
2 ,
26.3351 ,
17.228331 ,
3 ,
2 ,
47.166 ,
9.555373 ,
733 ,
2 ,
55.169438 ,
23.881275 ,
591 ,
2 ,
49.815273 ,
6.129583 ,
568 ,
2 ,
56.879635 ,
24.603189 ,
916 ,
2 ,
31.791702 ,
-7.09262 ,
215 ,
2 ,
47.411631 ,
28.369885 ,
212 ,
2 ,
-18.766947 ,
46.869107 ,
364 ,
2 ,
3.202778 ,
73.22068 ,
58 ,
2 ,
29.2985278 ,
42.5509603 ,
36 ,
2 ,
23.634501 ,
-102.552784 ,
577 ,
2 ,
36.958014 ,
-94.793619 ,
544 ,
2 ,
41.608635 ,
21.745275 ,
672 ,
2 ,
17.570692 ,
-3.996166 ,
67 ,
2 ,
35.937496 ,
14.375416 ,
19 ,
2 ,
21.916221 ,
95.955974 ,
755 ,
2 ,
46.862496 ,
103.846656 ,
138 ,
2 ,
-18.665695 ,
35.529562 ,
819 ,
2 ,
21.00789 ,
-10.940835 ,
4 ,
2 ,
-20.348404 ,
57.552152 ,
323 ,
2 ,
-13.254308 ,
34.301525 ,
567 ,
2 ,
4.210484 ,
101.975766 ,
1147 ,
2 ,
-22.95764 ,
18.49041 ,
143 ,
2 ,
-20.904305 ,
165.618042 ,
779 ,
2 ,
17.607789 ,
8.081666 ,
16 ,
2 ,
9.081999 ,
8.675277 ,
131 ,
2 ,
12.865416 ,
-85.207229 ,
440 ,
2 ,
52.132633 ,
5.291266 ,
190 ,
2 ,
60.472024 ,
8.468946 ,
563 ,
2 ,
28.394857 ,
84.124008 ,
431 ,
2 ,
-40.900557 ,
174.885971 ,
655 ,
2 ,
21.4735329 ,
55.975413 ,
1 ,
2 ,
30.375321 ,
69.345116 ,
33 ,
2 ,
8.537981 ,
-80.782127 ,
1054 ,
2 ,
-9.189967 ,
-75.015152 ,
981 ,
2 ,
12.879721 ,
121.774017 ,
458 ,
2 ,
7.51498 ,
134.58252 ,
1487 ,
2 ,
40.339852 ,
127.510093 ,
709 ,
2 ,
39.399872 ,
-8.224454 ,
590 ,
2 ,
-23.442503 ,
-58.443832 ,
655 ,
2 ,
29.9714142 ,
31.2213144 ,
27 ,
2 ,
45.943161 ,
24.96676 ,
507 ,
2 ,
61.52401 ,
105.318756 ,
845 ,
2 ,
-1.940278 ,
29.873888 ,
331 ,
2 ,
23.885942 ,
45.079162 ,
8 ,
2 ,
12.862807 ,
30.217636 ,
138 ,
2 ,
14.497401 ,
-14.452362 ,
729 ,
2 ,
1.352083 ,
103.819836 ,
392 ,
2 ,
-9.64571 ,
160.156194 ,
1325 ,
2 ,
5.152149 ,
46.199616 ,
173 ,
2 ,
44.016521 ,
21.005859 ,
528 ,
2 ,
0.18636 ,
6.613081 ,
948 ,
2 ,
3.919305 ,
-56.027783 ,
1668 ,
2 ,
48.669026 ,
19.699024 ,
685 ,
2 ,
46.151241 ,
14.995463 ,
1052 ,
2 ,
60.128161 ,
18.643501 ,
1170 ,
2 ,
-26.522503 ,
31.465866 ,
578 ,
2 ,
15.454166 ,
18.732207 ,
67 ,
2 ,
8.619543 ,
0.824782 ,
59 ,
2 ,
15.870032 ,
100.992541 ,
545 ,
2 ,
38.861034 ,
71.276093 ,
51 ,
2 ,
38.969719 ,
59.556278 ,
150 ,
2 ,
-21.178986 ,
-175.198242 ,
213 ,
2 ,
33.886917 ,
9.537499 ,
114 ,
2 ,
38.963745 ,
35.243322 ,
259 ,
2 ,
-7.109535 ,
177.64933 ,
566 ,
2 ,
-6.369028 ,
34.888822 ,
883 ,
2 ,
1.373333 ,
32.290275 ,
177 ,
2 ,
48.379433 ,
31.1655799 ,
283 ,
2 ,
-32.522779 ,
-55.765835 ,
180 ,
2 ,
37.09024 ,
-95.712891 ,
576 ,
2 ,
41.377491 ,
64.585262 ,
129 ,
2 ,
14.058324 ,
108.277199 ,
809 ,
2 ,
-15.376706 ,
166.959158 ,
613 ,
2 ,
-30.559482 ,
22.937506 ,
130 ,
2 ,
-13.133897 ,
27.849332 ,
1110 ,
2 ,
-19.015438 ,
29.154857 ,
618 ,
2 ,

In [25]:
data=pd.read_csv('visualnew.csv')

In [39]:
data.head(5)

         country        lat         lon  2013/14  2014/15  2015/16
0          China  35.861660  104.195397    87895    89540    91215
1       Malaysia   4.210484  101.975766    16635    17060    17405
2  United States  37.090240  -95.712891    16485    16865    17115
3          India  20.593684   78.962880    19750    18325    16745
4     Hong Kong   22.396428  114.109497    14725    16215    16745

In [42]:
from sklearn import preprocessing

In [45]:
output

array([[ 1.        ,  1.        ,  1.        ],
       [ 0.13827922,  0.14016252,  0.13733053],
       [ 0.13646532,  0.13784922,  0.13394109],
       [ 0.17594776,  0.15516935,  0.12961664],
       [ 0.1151823 ,  0.13013821,  0.12961664],
       [ 0.15502751,  0.15036479,  0.12207807],
       [ 0.04667755,  0.03974138,  0.03406966],
       [ 0.01922728,  0.02431935,  0.02203132],
       [ 0.0137856 ,  0.01180378,  0.00514259],
       [ 0.01390652,  0.00984637,  0.0037985 ],
       [ 0.1071407 ,  0.10000593,  0.09081346],
       [ 0.07618357,  0.0796014 ,  0.08029453],
       [ 0.05260294,  0.06263717,  0.07573633],
       [ 0.07606264,  0.06714515,  0.05364656],
       [ 0.06614668,  0.05795124,  0.04832866],
       [ 0.01674829,  0.02129426,  0.02553763],
       [ 0.01590181,  0.01595587,  0.0180575 ],
       [ 0.01396699,  0.01198173,  0.00631136],
       [ 0.        ,  0.        ,  0.        ]])